export const queryKeys = {
  activitati: ['activitati'] as const,
  culturi: (solarId: string) => ['culturi', solarId] as const,
  culturiCounts: (scope: string) => ['culturi-counts', scope] as const,
  culturiTreatmentIntervals: (scope: string) => ['culturi-treatment-intervals', scope] as const,
  etapeCultura: (culturaId: string) => ['etape-cultura', culturaId] as const,
  activitatiAgricole: ['activitati'] as const,
  cheltuieli: ['cheltuieli'] as const,
  clienti: ['clienti'] as const,
  comenzi: ['comenzi'] as const,
  comenziStockSummaryAzi: ['comenzi', 'stock-summary-azi'] as const,
  culegatori: ['culegatori'] as const,
  crops: (tipUnitate: string) => ['crops', tipUnitate] as const,
  cropVarieties: (cropId: string | null) => ['crop-varieties', cropId] as const,
  dashboard: ['dashboard'] as const,
  investitii: ['investitii'] as const,
  meteo: ['meteo'] as const,
  miscariStoc: ['miscari-stoc'] as const,
  currentUserProfile: ['current-user-profile'] as const,
  parcela: (parcelaId: string) => ['parcela', parcelaId] as const,
  parcelaCultureStages: (parcelaId: string) => ['parcela', parcelaId, 'culture-stages'] as const,
  parcelaSolarClimate: (parcelaId: string) => ['parcela', parcelaId, 'solar-climate'] as const,
  parcele: ['parcele'] as const,
  recoltari: ['recoltari'] as const,
  solarClimate: (scope: string) => ['solar-climate', scope] as const,
  solarStages: (scope: string) => ['solar-stages', scope] as const,
  stocGlobal: ['stoc-global'] as const,
  stocGlobalCal1: ['stoc-global-cal1'] as const,
  stocuriLocatiiRoot: ['stocuri-locatii'] as const,
  stocuriLocatii: (filtersKey: unknown) => ['stocuri-locatii', filtersKey] as const,
  subscriptionPlanTenant: ['subscription-plan', 'tenant'] as const,
  produse: ['produse'] as const,
  produseActiv: ['produse', 'activ'] as const,
  vanzari: ['vanzari'] as const,
  vanzariButasi: ['vanzari-butasi'] as const,
}
