project_id = "zmeurel"

[api]
enabled = true
port = 54321

[db]
port = 54322

[db.pooler]
enabled = false

[studio]
enabled = false
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_confirmations = false

[edge_runtime]
enabled = false
