BEGIN;

INSERT INTO public.reguli_recomandare_platforma (
  cod,
  cultura_tip,
  fenofaza,
  metoda_aplicare,
  cohort,
  luni_active,
  titlu,
  descriere,
  produs_sugerat_nume,
  produs_sugerat_doza_text,
  tip_interventie,
  prioritate,
  sursa
)
VALUES
  (
    'zmeur_drosophila_capcana_coacere',
    'zmeur',
    'parga',
    'capcana_pus',
    NULL,
    NULL,
    'Capcană Drosophila',
    'La apropiere coacere, Drosophila suzukii devine principalul risc. Capcanele cu oțet/vin de mere atrag și monitorizează populația.',
    'Capcană oțet (DIY sau Riga Cherry)',
    '10 capcane/ha',
    'monitorizare',
    90,
    'standard_agronomic'
  ),
  (
    'zmeur_drosophila_capcana_maturitate',
    'zmeur',
    'maturitate',
    'capcana_pus',
    NULL,
    NULL,
    'Capcană Drosophila intensiv',
    'În perioada de recoltare, densitatea capcanelor poate crește la 15/ha pentru atragere maximă.',
    'Capcană oțet',
    '15 capcane/ha',
    'monitorizare',
    95,
    'standard_agronomic'
  ),
  (
    'zmeur_cupric_primavara',
    'zmeur',
    'umflare_muguri',
    'foliar',
    NULL,
    ARRAY[2, 3, 4]::integer[],
    'Tratament cupric primăvară',
    'Tratament igienă obligatoriu la dezmugurire pentru prevenire bacterioze și fungi de iarnă (verticilioză, antracnoză).',
    'Zeamă bordeleză (sau Funguran)',
    '5 kg/ha',
    'igiena',
    85,
    'standard_agronomic'
  ),
  (
    'zmeur_acarian_buton_verde',
    'zmeur',
    'buton_verde',
    'foliar',
    NULL,
    NULL,
    'Acarian Phyllocoptes gracilis',
    'Acarianul roșu apare devreme pe muguri. Tratamentul preventiv blochează populația înainte să se extindă pe frunze.',
    'Vertimec 1.8 EC (sau Milbeknock)',
    '1.2 L/ha',
    'protectie',
    80,
    'practica_andrei'
  ),
  (
    'zmeur_botritis_etaj_floral',
    'zmeur',
    'etaj_floral',
    'foliar',
    NULL,
    NULL,
    'Botritis preventiv',
    'În perioada etajului floral, prevenția botritis-ului trebuie făcută înainte de deschiderea florilor. Switch acoperă și antracnoza.',
    'Switch 62.5 WG (sau Signum)',
    '0.6 kg/ha',
    'protectie',
    88,
    'standard_agronomic'
  ),
  (
    'zmeur_trips_inflorit',
    'zmeur',
    'inflorit',
    'foliar',
    NULL,
    NULL,
    'Trips în floare',
    'Tripsul atacă florile direct, reduce legarea fructelor. Tratamentul trebuie aplicat seara, când albinele nu zboară.',
    'Laser 240 SC (sau Movento)',
    '0.2 L/ha',
    'protectie',
    75,
    'standard_agronomic'
  ),
  (
    'zmeur_calciu_legare_fruct',
    'zmeur',
    'legare_fruct',
    'fertirigare',
    NULL,
    NULL,
    'Calciu pentru fruct ferm',
    'Aportul de calciu la legarea fructelor crește fermitatea, scade probabilitatea de zdrobire la recoltare și transport.',
    'Calcinit (15-0-0 + 26 CaO)',
    '1.5 kg/parcelă',
    'nutritie',
    70,
    'practica_andrei'
  ),
  (
    'zmeur_kalium_fruct_verde',
    'zmeur',
    'fruct_verde',
    'fertirigare',
    NULL,
    NULL,
    'Potasiu pentru aromă și calibru',
    'Potasiul în faza de creștere a fructului dezvoltă aroma, dulceața și calibrul final. Aplicare regulată, nu o singură doză mare.',
    'Kristalon Roșu (12-12-36)',
    '2 kg/parcelă',
    'nutritie',
    72,
    'standard_agronomic'
  ),
  (
    'zmeur_megafol_parga_vara',
    'zmeur',
    'parga',
    'foliar',
    NULL,
    ARRAY[7, 8]::integer[],
    'Anti-stres termic (Megafol)',
    'Pe canicula de iulie-august, biostimulatorii cu aminoacizi reduc stresul plantei și mențin calitatea fructelor.',
    'Megafol (Valagro)',
    '2 L/ha',
    'biostimulare',
    65,
    'practica_andrei'
  ),
  (
    'zmeur_refacere_post_recoltare',
    'zmeur',
    'post_recoltare',
    'fertirigare',
    NULL,
    NULL,
    'Refacere plantă post-recoltare',
    'După recoltare, planta și-a epuizat rezervele. Mix K+P stimulează formarea mugurilor pentru anul următor.',
    'KNO3 + MAP',
    '2 + 1 kg/parcelă',
    'nutritie',
    78,
    'standard_agronomic'
  ),
  (
    'zmeur_tratament_iarna',
    'zmeur',
    'repaus_vegetativ',
    'foliar',
    NULL,
    ARRAY[11, 12, 1, 2]::integer[],
    'Tratament cupric iarnă',
    'Tratament obligatoriu în perioada de repaus pentru curățarea fungilor de pe lăstari și sol. Doză mai mare decât primăvara.',
    'Zeamă bordeleză',
    '7 kg/ha',
    'igiena',
    82,
    'standard_agronomic'
  )
ON CONFLICT (cod) DO UPDATE SET
  cultura_tip = EXCLUDED.cultura_tip,
  fenofaza = EXCLUDED.fenofaza,
  metoda_aplicare = EXCLUDED.metoda_aplicare,
  cohort = EXCLUDED.cohort,
  luni_active = EXCLUDED.luni_active,
  titlu = EXCLUDED.titlu,
  descriere = EXCLUDED.descriere,
  produs_sugerat_nume = EXCLUDED.produs_sugerat_nume,
  produs_sugerat_doza_text = EXCLUDED.produs_sugerat_doza_text,
  tip_interventie = EXCLUDED.tip_interventie,
  prioritate = EXCLUDED.prioritate,
  sursa = EXCLUDED.sursa,
  activ = true,
  updated_at = now();

COMMIT;
