'use client'

import { useState } from 'react'

import { colors } from '@/lib/design-tokens'
import type { Cheltuiala } from '@/lib/supabase/queries/cheltuieli'
import { isAutoManoperaCheltuiala } from '@/lib/supabase/queries/manopera-auto'

interface CheltuialaCardProps {
  cheltuiala: Cheltuiala
  onView: (cheltuiala: Cheltuiala) => void
  onEdit: (cheltuiala: Cheltuiala) => void
  onDelete: (id: string, name: string) => void
}

const CATEGORY_EMOJI: Record<string, string> = {
  tratamente: '🧪',
  fertilizare: '🌱',
  manopera: '👷',
  transport: '🚛',
  'material saditor': '🌿',
  echipamente: '🔧',
  combustibil: '⛽',
  altele: '📦',
}

function normalizeCategory(value: string | null | undefined): string {
  return (value ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
}

export function getCheltuialaCategoryEmoji(category: string | null | undefined): string {
  const normalized = normalizeCategory(category)
  if (normalized.includes('trat')) return CATEGORY_EMOJI.tratamente
  if (normalized.includes('fert')) return CATEGORY_EMOJI.fertilizare
  if (normalized.includes('manopera') || normalized.includes('cules')) return CATEGORY_EMOJI.manopera
  if (normalized.includes('transport') || normalized.includes('motorina')) return CATEGORY_EMOJI.transport
  if (normalized.includes('saditor')) return CATEGORY_EMOJI['material saditor']
  if (normalized.includes('echip') || normalized.includes('scule') || normalized.includes('utilaje')) return CATEGORY_EMOJI.echipamente
  if (normalized.includes('combustibil') || normalized.includes('carburant')) return CATEGORY_EMOJI.combustibil
  return CATEGORY_EMOJI.altele
}

function getAmountBorderColor(amount: number): string {
  if (amount > 500) return colors.coral
  if (amount >= 200) return colors.yellow
  return colors.grayLight
}

export function CheltuialaCard({ cheltuiala, onView, onEdit, onDelete }: CheltuialaCardProps) {
  const [expanded, setExpanded] = useState(false)
  const categorie = cheltuiala.categorie || 'Altele'
  const suma = Number(cheltuiala.suma_lei || 0)
  const isAutoGenerated = isAutoManoperaCheltuiala(cheltuiala)
  const categoryEmoji = getCheltuialaCategoryEmoji(categorie)
  const borderColor = getAmountBorderColor(suma)
  const description = cheltuiala.descriere || cheltuiala.furnizor || 'Fără detalii'
  const dataLabel = cheltuiala.data ? new Date(cheltuiala.data).toLocaleDateString('ro-RO') : '-'

  return (
    <div
      className="overflow-hidden rounded-2xl border bg-white shadow-sm"
      style={{ borderColor: 'var(--agri-border)', borderLeft: `4px solid ${borderColor}` }}
    >
      <button
        type="button"
        onClick={() => setExpanded((prev) => !prev)}
        className="w-full p-5 text-left"
      >
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--agri-surface-muted)] text-lg">
            {categoryEmoji}
          </div>

          <div className="min-w-0 flex-1 space-y-1.5">
            <div className="truncate text-sm font-semibold text-[var(--agri-text)]">{description}</div>
            <div className="text-sm text-[var(--agri-text-muted)]">{categorie}</div>
          </div>

          <div className="shrink-0 text-right">
            <div className="text-lg font-bold text-[var(--agri-text)]">{suma.toFixed(2)} RON</div>
            <div className="text-[10px] text-[var(--agri-text-muted)]">{dataLabel}</div>
          </div>
        </div>

        <div className="mt-4 flex items-center justify-between">
          <div className="min-h-[18px]">
            {isAutoGenerated ? (
              <span className="inline-flex items-center rounded-md bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">
                Auto
              </span>
            ) : null}
          </div>
          <span className="text-base text-[var(--agri-text-muted)]">{expanded ? '▴' : '▾'}</span>
        </div>
      </button>

      {expanded ? (
        <div className="grid gap-4 border-t border-[var(--agri-border)] bg-white px-5 py-5">
          <div className="text-sm text-[var(--agri-text-muted)]">
            <strong className="text-[var(--agri-text)]">Detalii:</strong> {description}
          </div>

          <div className="mt-4 grid grid-cols-3 gap-2">
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onView(cheltuiala)
              }}
              className="min-h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold text-slate-700"
            >
              Detalii
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onEdit(cheltuiala)
              }}
              className="min-h-11 rounded-xl border border-amber-200 bg-amber-50 px-3 text-sm font-semibold text-amber-800"
            >
              Editează
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onDelete(cheltuiala.id, `${categorie} - ${suma.toFixed(2)} RON`)
              }}
              className="min-h-11 rounded-xl border border-red-200 bg-red-50 px-3 text-sm font-semibold text-red-700"
            >
              Șterge
            </button>
          </div>
        </div>
      ) : null}
    </div>
  )
}
