'use client'

import { useState } from 'react'

import { colors, radius, shadows, spacing } from '@/lib/design-tokens'
import type { Cheltuiala } from '@/lib/supabase/queries/cheltuieli'
import { isAutoManoperaCheltuiala } from '@/lib/supabase/queries/manopera-auto'

interface CheltuialaCardProps {
  cheltuiala: Cheltuiala
  onView: (cheltuiala: Cheltuiala) => void
  onEdit: (cheltuiala: Cheltuiala) => void
  onDelete: (id: string, name: string) => void
}

const CATEGORY_EMOJI: Record<string, string> = {
  tratamente: '🧪',
  fertilizare: '🌱',
  manopera: '👷',
  transport: '🚛',
  'material saditor': '🌿',
  echipamente: '🔧',
  combustibil: '⛽',
  altele: '📦',
}

function normalizeCategory(value: string | null | undefined): string {
  return (value ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
}

export function getCheltuialaCategoryEmoji(category: string | null | undefined): string {
  const normalized = normalizeCategory(category)
  if (normalized.includes('trat')) return CATEGORY_EMOJI.tratamente
  if (normalized.includes('fert')) return CATEGORY_EMOJI.fertilizare
  if (normalized.includes('manopera') || normalized.includes('cules')) return CATEGORY_EMOJI.manopera
  if (normalized.includes('transport') || normalized.includes('motorina')) return CATEGORY_EMOJI.transport
  if (normalized.includes('saditor')) return CATEGORY_EMOJI['material saditor']
  if (normalized.includes('echip') || normalized.includes('scule') || normalized.includes('utilaje')) return CATEGORY_EMOJI.echipamente
  if (normalized.includes('combustibil') || normalized.includes('carburant')) return CATEGORY_EMOJI.combustibil
  return CATEGORY_EMOJI.altele
}

function getAmountBorderColor(amount: number): string {
  if (amount > 500) return colors.coral
  if (amount >= 200) return colors.yellow
  return colors.grayLight
}

export function CheltuialaCard({ cheltuiala, onView, onEdit, onDelete }: CheltuialaCardProps) {
  const [expanded, setExpanded] = useState(false)
  const categorie = cheltuiala.categorie || 'Altele'
  const suma = Number(cheltuiala.suma_lei || 0)
  const isAutoGenerated = isAutoManoperaCheltuiala(cheltuiala)
  const categoryEmoji = getCheltuialaCategoryEmoji(categorie)
  const borderColor = getAmountBorderColor(suma)
  const description = cheltuiala.descriere || cheltuiala.furnizor || 'Fără detalii'
  const dataLabel = cheltuiala.data ? new Date(cheltuiala.data).toLocaleDateString('ro-RO') : '-'

  return (
    <div
      style={{
        borderRadius: radius.lg,
        border: `1px solid ${colors.grayLight}`,
        borderLeft: `4px solid ${borderColor}`,
        boxShadow: shadows.card,
        background: colors.white,
        overflow: 'hidden',
      }}
    >
      <button
        type="button"
        onClick={() => setExpanded((prev) => !prev)}
        style={{
          width: '100%',
          border: 'none',
          background: 'transparent',
          textAlign: 'left',
          padding: spacing.md,
          cursor: 'pointer',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: spacing.sm }}>
          <div
            style={{
              width: 36,
              height: 36,
              borderRadius: radius.md,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: 17,
              background: colors.grayLight,
              flexShrink: 0,
            }}
          >
            {categoryEmoji}
          </div>

          <div style={{ minWidth: 0, flex: 1 }}>
            <div
              style={{
                fontSize: 14,
                fontWeight: 700,
                color: colors.dark,
                whiteSpace: 'nowrap',
                overflow: 'hidden',
                textOverflow: 'ellipsis',
              }}
            >
              {description}
            </div>
            <div style={{ fontSize: 11, color: colors.gray }}>{categorie}</div>
          </div>

          <div style={{ textAlign: 'right', flexShrink: 0 }}>
            <div style={{ fontSize: 16, fontWeight: 700, color: colors.dark }}>{suma.toFixed(2)} RON</div>
            <div style={{ fontSize: 10, color: colors.gray }}>{dataLabel}</div>
          </div>
        </div>

        <div style={{ marginTop: spacing.sm, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ minHeight: 18 }}>
            {isAutoGenerated ? (
              <span
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  borderRadius: radius.sm,
                  padding: '2px 6px',
                  fontSize: 10,
                  fontWeight: 700,
                  color: colors.blue,
                  background: colors.blueLight,
                }}
              >
                🤖 Auto
              </span>
            ) : null}
          </div>
          <span
            style={{
              fontSize: 16,
              color: colors.gray,
              transform: expanded ? 'rotate(180deg)' : 'rotate(0deg)',
              transition: 'transform 180ms ease',
            }}
          >
            ▾
          </span>
        </div>
      </button>

      {expanded ? (
        <div
          style={{
            borderTop: `1px solid ${colors.grayLight}`,
            padding: `${spacing.sm}px ${spacing.md}px ${spacing.md}px`,
            display: 'grid',
            gap: spacing.sm,
          }}
        >
          <div style={{ fontSize: 11, color: colors.gray }}>
            <strong style={{ color: colors.dark }}>Detalii:</strong> {description}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: spacing.sm }}>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onView(cheltuiala)
              }}
              style={{
                minHeight: 48,
                border: 'none',
                borderRadius: radius.md,
                background: colors.grayLight,
                color: colors.dark,
                fontSize: 12,
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              👁️ Detalii
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onEdit(cheltuiala)
              }}
              style={{
                minHeight: 48,
                border: 'none',
                borderRadius: radius.md,
                background: colors.yellowLight,
                color: colors.dark,
                fontSize: 12,
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              ✏️ Edit
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onDelete(cheltuiala.id, `${categorie} - ${suma.toFixed(2)} RON`)
              }}
              style={{
                minHeight: 48,
                border: 'none',
                borderRadius: radius.md,
                background: colors.coralLight,
                color: colors.coral,
                fontSize: 12,
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              🗑️ Șterge
            </button>
          </div>
        </div>
      ) : null}
    </div>
  )
}
