'use client'

import { memo, useState } from 'react'

import { colors } from '@/lib/design-tokens'
import type { Cheltuiala } from '@/lib/supabase/queries/cheltuieli'
import { isAutoManoperaCheltuiala } from '@/lib/supabase/queries/manopera-auto'

interface CheltuialaCardProps {
  cheltuiala: Cheltuiala
  onView: (cheltuiala: Cheltuiala) => void
  onEdit: (cheltuiala: Cheltuiala) => void
  onDelete: (id: string, name: string) => void
}

function normalizeCategory(value: string | null | undefined): string {
  return (value ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
}

export function getCheltuialaCategoryEmoji(category: string | null | undefined): string {
  const n = normalizeCategory(category)
  if (n.includes('trat') || n.includes('fitosanitar') || n.includes('pesticid')) return '🧪'
  if (n.includes('fert')) return '🌱'
  if (n.includes('forta') || n.includes('munca') || n.includes('manopera') || n.includes('cules')) return '👷'
  if (n.includes('transport') || n.includes('livrare') || n.includes('motorina')) return '🚛'
  if (n.includes('reparati') || n.includes('intretinere') || n.includes('service')) return '🔧'
  if (n.includes('combustibil') || n.includes('carburant') || n.includes('energie') || n.includes('electric')) return '⛽'
  if (n.includes('ambalaj') || n.includes('cutie') || n.includes('folie')) return '📦'
  if (n.includes('consumabil') || n.includes('scul') || n.includes('unealt')) return '🛠️'
  if (n.includes('servicii') || n.includes('taxa') || n.includes('impozit') || n.includes('asigurare')) return '🏛️'
  // legacy fallbacks (date vechi din DB înainte de migrare)
  if (n.includes('saditor') || n.includes('butas')) return '🌿'
  if (n.includes('echip') || n.includes('utilaj')) return '🔧'
  return '📦'
}

function getAmountBorderColor(amount: number): string {
  if (amount > 500) return colors.coral
  if (amount >= 200) return colors.yellow
  return colors.grayLight
}

export function CheltuialaCard({ cheltuiala, onView, onEdit, onDelete }: CheltuialaCardProps) {
  const [expanded, setExpanded] = useState(false)
  const categorie = cheltuiala.categorie || 'Altele'
  const suma = Number(cheltuiala.suma_lei || 0)
  const isAutoGenerated = isAutoManoperaCheltuiala(cheltuiala)
  const categoryEmoji = getCheltuialaCategoryEmoji(categorie)
  const borderColor = getAmountBorderColor(suma)
  const description = cheltuiala.descriere || cheltuiala.furnizor || 'Fără detalii'
  const dataLabel = cheltuiala.data ? new Date(cheltuiala.data).toLocaleDateString('ro-RO') : '-'

  return (
    <div
      className="overflow-hidden rounded-2xl border bg-[var(--agri-surface)] shadow-sm"
      style={{ borderColor: 'var(--agri-border)', borderLeft: `4px solid ${borderColor}` }}
    >
      <button
        type="button"
        onClick={() => setExpanded((prev) => !prev)}
        className="w-full p-5 text-left"
      >
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--agri-surface-muted)] text-lg">
            {categoryEmoji}
          </div>

          <div className="min-w-0 flex-1 space-y-1.5">
            <div className="truncate text-sm font-semibold text-[var(--agri-text)]">{description}</div>
            <div className="text-sm text-[var(--agri-text-muted)]">{categorie}</div>
          </div>

          <div className="shrink-0 text-right">
            <div className="text-lg font-bold text-[var(--agri-text)]">{suma.toFixed(2)} RON</div>
            <div className="text-[10px] text-[var(--agri-text-muted)]">{dataLabel}</div>
          </div>
        </div>

        <div className="mt-4 flex items-center justify-between">
          <div className="min-h-[18px]">
            {isAutoGenerated ? (
              <span className="inline-flex items-center rounded-md border border-[var(--status-info-border)] bg-[var(--status-info-bg)] px-2 py-1 text-[10px] font-bold text-[var(--status-info-text)]">
                Auto
              </span>
            ) : null}
          </div>
          <span className="text-base text-[var(--agri-text-muted)]">{expanded ? '▴' : '▾'}</span>
        </div>
      </button>

      {expanded ? (
        <div className="grid gap-4 border-t border-[var(--surface-divider)] bg-[var(--agri-surface)] px-5 py-5">
          <div className="text-sm text-[var(--agri-text-muted)]">
            <strong className="text-[var(--agri-text)]">Detalii:</strong> {description}
          </div>

          <div className="mt-4 grid grid-cols-3 gap-2">
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onView(cheltuiala)
              }}
              className="min-h-11 rounded-xl border border-[var(--button-muted-border)] bg-[var(--button-muted-bg)] px-3 text-sm font-semibold text-[var(--button-muted-text)]"
            >
              Detalii
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onEdit(cheltuiala)
              }}
              className="min-h-11 rounded-xl border border-[var(--status-warning-border)] bg-[var(--status-warning-bg)] px-3 text-sm font-semibold text-[var(--status-warning-text)]"
            >
              Editează
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation()
                onDelete(cheltuiala.id, `${categorie} - ${suma.toFixed(2)} RON`)
              }}
              className="min-h-11 rounded-xl border border-[var(--status-danger-border)] bg-[var(--status-danger-bg)] px-3 text-sm font-semibold text-[var(--status-danger-text)]"
            >
              Șterge
            </button>
          </div>
        </div>
      ) : null}
    </div>
  )
}

export default memo(CheltuialaCard)
