export const STOCK_AUDIT_LOW_STOCK_THRESHOLD_KG = 20
export const STOCK_AUDIT_SYNC_DELTA_THRESHOLD_KG = 1
export const STOCK_AUDIT_ADJUSTMENT_SHARE_THRESHOLD = 0.15
export const STOCK_AUDIT_MIN_ADJUSTMENT_ABS_THRESHOLD_KG = 20
export const STOCK_AUDIT_NEGATIVE_STOCK_EPSILON_KG = 0.01
